services:
  hello_app:
    build: ./hello_app
    ports:
      - "8080"

  hello_app_response:
    build: ./hello_app_response
    ports:
      - "8081"

  reverse_proxy:
    build: ./reverse_proxy
    ports:
     - "8083:80"
